### PR TITLE
edit npm start based on task runner #147

### PR DESCRIPTION
**Pull request by theolampert**
fixes https://github.com/keystonejs/generator-keystone/issues/147

### CODE REVIEW

**Comment by morenoh149** [comment]
lgtm

**Comment by theolampert** [comment]
@morenoh149 thats correct.

**Comment by morenoh149** [comment]
@theolampert mind updating? I'd love to see this integrated. Fixes https://github.com/keystonejs/generator-keystone/issues/166

**Comment by mxstbr** [comment]
@theolampert could you rebase this onto master so we can merge it? Would love to land this with the next release!

**Comment by mxstbr** [comment]
Also, a fix for #166 was landed individually in #184, might need to check that `taskrunner` isn't `none`!

**Comment by theolampert** [comment]
@mxstbr sure - I'm at work right now so I'll patch this later today if thats ok.

**Comment by mxstbr** [comment]
Awesome, sounds good to me! Thanks!

**Comment by theolampert** [comment]
should be good to go

**Comment by mxstbr** [comment]
Awesome, thanks so much!

**Pull request merged**
