### PR TITLE
Change cmd from npm start to node keystone

### PR DESCRIPTION
**Pull request by heathernfran**
Updated console.log instructions to output "node keystone", instead of "npm start", on ln 28.

See step 3 in the KeystoneJS [Getting Started](http://keystonejs.com/getting-started/) guide.

### CODE REVIEW

**Comment by morenoh149** [comment]
@heathernfran was this requested? In my opinion both instructions hold equal merit.

**Comment by heathernfran** [comment]
It was something I came across when following the generator instructions (as opposed to getting started guide).  The update was more for consistency between Keystone and its generator.

The issue was originally brought up in the KeystoneJS project [here](https://github.com/keystonejs/keystone/issues/2889)

**Comment by morenoh149** [comment]
Ah if there's an inconsistency then that should definitely be addressed.

**Comment by mxstbr** [comment]
Could you undo the whitespace changes?

**Comment by heathernfran** [comment]
@mxstbr please use #206 instead, thanks

**Pull request closed without merging**
