### PR TITLE
Fixtwig

### PR DESCRIPTION
**Pull request by r3wt**
This PR should fix the inability to select twig when creating a new project. It does not remove swig so it should be safe to merge into master.

some key things to note:

- added conditional to allow selecting twig in `/app/index.js` 
- added spaceless/endspaceless to `/layouts/default.twig` to minify the output by default. 
- cleaned up the templates a bit.
- fixed the macro's in `/mixins/flash-messages.twig`. in twig, a macro must be imported as self to be used from within the context of another macro.
- removed the comments from `/layouts/default.twig` see [https://github.com/twigjs/twig.js/issues/379] for my reasoning. basically comments are broken atm in twig.js, although its not known to cause any problems, its best to err on the side of caution. a twig developer should be able to understand the code of this particular file without the need for comments as its very straightforward.

RE: https://github.com/keystonejs/keystone/issues/2967

### CODE REVIEW

**Comment by JedWatson** [comment]
Looks great @r3wt, thanks! Really appreciate it.

I think it would be fine to merge this and then do another one to remove swig... or is there a reason I missed we're delaying that? (cc @mxstbr)

**Comment by JedWatson** [comment]
To clarify (after re-reading the keystone issue you linked above) when I was talking about 0.3 vs 0.4 releases, I meant keystone itself, which this doesn't impact. I don't actually think there's such a thing as a breaking change to a generator... Happy to drop swig asap given twig is in and works!

**Comment by mxstbr** [comment]
Ah yeah, true, I forgot you can break a generator… My bad!

**Comment by r3wt** [comment]
@JedWatson alright, buddy. coming right up!

**Pull request merged**
