### PR TITLE
Added support for Stylus in Gulp

### PR DESCRIPTION
**Pull request by micahbule**
Added generated code for Stylus support in gulpfile.js

To-do:
- Add support for Stylus in Grunt option
- Add prompt for Nib support if Stylus option is used

### CODE REVIEW

**Comment by morenoh149** [comment]
@micahbule awesome. Does this fix https://github.com/keystonejs/keystone/issues/183 ?

**Comment by micahbule** [comment]
If you're talking about Stylus integration with the underlying Express framework using Connect middleware, no, this is not it.

I just followed the pattern used for the Sass integration with the Yeoman generator and added a compiler for Stylus using Gulp. I still have to work on the Grunt task option. Also, I searched the repo for Stylus issues, and I found out that some people do need support for Nib (https://github.com/tj/nib), so I threw that in my to-do list too.

Someone added the Stylus option in the Yeoman generator, as well as Stylus resource files (Bootstrap), but I think they missed adding them to the task runners (Gulp/Grunt), so when you generate a project, there's no out-of-the-box support for Stylus.

**Comment by morenoh149** [comment]
@micahbule yeah. support is spotty. I thought issue https://github.com/keystonejs/keystone/issues/183 had to do with just adding stylus to a keystone project. Not sure what adding the middleware to the express instance would offer beyond that. As long as a user can use stylus or sass with a keystone project that should be the goal right? Afaik.

**Comment by micahbule** [comment]
I probably just misread the issue. I've been working on Express with a Stylus middleware so I had different assumptions.

If that's the case, this PR should work at least for compiling using Gulp.

**Comment by JedWatson** [comment]
Thanks @micahbule, much appreciated!

**Pull request merged**
