### PR TITLE
remove swig and fix inability to select twig

### PR DESCRIPTION
**Pull request by r3wt**
RE: #180 
1. My initial commit enabling the use of twig was incomplete. see `/app/index.js` for fix.
2. Removes swig.

### CODE REVIEW

**Comment by mxstbr** [comment]
Awesome!

**Comment by r3wt** [comment]
this pr is STILL broken. i'll wait until this can be merged then rebase and fix it.

**Comment by JedWatson** [comment]
@r3wt this should be good to merge now after rebase?

**Comment by geloescht** [comment]
@r3wt What issues did you run into trying to rebase this PR?

**Comment by r3wt** [comment]
closing this. i'll rebase and remove swig as discussed in my other pr.

**Pull request closed without merging**
