### PR TITLE
Generate Cryptographically secure cookie secret

### PR DESCRIPTION
**Pull request by morenoh149**
* closes https://github.com/keystonejs/generator-keystone/issues/144

### CODE REVIEW

**Comment by morenoh149** [comment]
see http://stackoverflow.com/questions/8855687/secure-random-token-in-node-js

**Comment by ericelliott** [comment]
:+1: Do we also need this in the React generator? I believe that dumped a token right into my `keystone.js` file yesterday. ;)

**Comment by ericelliott** [comment]
@JedWatson

**Comment by JedWatson** [comment]
Nice one @morenoh149!

@ericelliott yeah - I'll copy this across into the React generator and release a new version of both.

**Comment by ericelliott** [comment]
:+1:

**Pull request merged**
