### PR TITLE
Add images to blog posts

### LINKED ISSUE #173: Hbs blog template does not show images
The [jade blog template](https://github.com/keystonejs/generator-keystone/blob/master/app/templates/templates/default-jade/views/blog.jade#L20) includes the image for the blog post (if there is one), however this does not happen in the [handlebars template](https://github.com/keystonejs/generator-keystone/blob/master/app/templates/templates/default-hbs/views/blog.hbs). 

I feel like they should both do the same thing, and showing the image seems nice.

This is also the case in the post templates themselves - jade automatically adds the image to the bottom of the post whereas the handlebars template does not.  

Happy to PR a fix, although would appreciate some pointers on the hbs equivalent of jade's `img.fit(160, 160)` if one exists.

### PR DESCRIPTION
**Pull request by jstockwin**
Fixes #173

### CODE REVIEW

**Comment by mxstbr** [comment]
Did you manage to test this? Looks :+1:!

**Comment by jstockwin** [comment]
I copied the changed template files into an existing project, and it displayed fine and the html source code looked correct to me, so yeah I've tested it. Never actually managed to get a local version of the generator to 'generate' as such, but that doesn't really matter.

**Comment by jstockwin** [comment]
Although now we're using the cloudinaryUrl stuff we're going to hit against #176 (which I actually noticed when testing this...)

**Comment by mxstbr** [comment]
I'll merge this for now, do you want to try to take a look at #176?

**Comment by jstockwin** [comment]
@mxstbr I'll happily have a look, but wouldn't really know where to start. I don't really have any experience - this is all new to me, but I am interested to learn. 

My immediate 'fix' would be to add a line of code above [here](https://github.com/keystonejs/generator-keystone/blob/master/app/templates/templates/default-hbs/views/helpers/index.js#L181) that checks if keystone 'cloudinary secure' has been set, and appends 'secure=true' to options if it has. But I wouldn't really know how to access keystone.set config options, and this seems like a bad way of doing things anyway. 

The words `cloudinary secure` don't appear anywhere in the generator-keystone repository... the only instance I can find of a check is [here](https://github.com/keystonejs/keystone/blob/811e6b3e0914562440f8866feb57fbd5a2211a04/admin/server/api/cloudinary.js#L18). 

Anyway, I'll have a play, but feel like I will probably end up with an inadequate/hacky solution without quite a few pointers...

**Comment by mxstbr** [comment]
I can't push you in the correct way at the moment since I'm not sure what's causing the issue myself and I can't prioritize it currently. :/

Definitely submit a PR and I'll take a look and see if it makes sense or if we can come up with a nicer solution maybe!

**Comment by jstockwin** [comment]
Yes that's fine. I wasn't expecting you to. What I mean is I can do somethings easily enough, e.g. the e2e testing where there are basic examples already in place for me to understand how they work, but for stuff like this I get a little lost. 

I'm very aware that I am new to this, and that you guys are busy and don't have time to spare, so don't want to start PRing code that's a bit useless, or that I think is probably not the best way of doing things. However, I'm keen to help out where I can, and if I can save you work that's great. But there becomes a point where I feel like the amount of questions I'd have to ask to be able to get a solution will take more time than one of you guys just fixing it. 

As I said, I'll have a play tomorrow. At the very least, I'll check if the problem is restricted to handlebars, or if it's a wider problem. Hopefully, I'll be able to find a way to fix it, but again, I feel the way I'd do it is probably a bit hacky and forced instead of addressing any underlying problems.

**Comment by mxstbr** [comment]
Don't worry about it, teaching new contributors about the code base is probably one of the most important things good OSS maintainers can do, so I absolutely don't mind, shoot all the questions at me! Are you on the Keystone Dev Slack already?

**Comment by jstockwin** [comment]
I am not. Have never used Slack, will sign up!

**Comment by jstockwin** [comment]
Okay, so it's not a "sign up" thing :+1:  Can you add jstockwin@gmail.com to the team or whatever needs to happen...

**Comment by mxstbr** [comment]
I've invited you—whenever you have a question ping me there, that's probably the fastest way to get a response! (or on [twitter](https://twitter.com/mxstbr)

**Pull request merged**
