### PR TITLE
Implemented handlerbars enquiry-notification template.

### PR DESCRIPTION
**Pull request by jeffreypriebe**
Also added underscoreFormat helper method to support enquiry-notification template.

### CODE REVIEW

**Comment by JedWatson** [comment]
Thanks @jeffreypriebe!

**Comment by JedWatson** [comment]
Does this close #98?

**Comment by jeffreypriebe** [comment]
@JedWatson Happy to help.
Short answer on #98: "No, doesn't close it." I feel like #98 is three parts:
 1. [x] This issue (missing template).
 2. [ ] Handlebars misconfigured in generator, fix in https://github.com/keystonejs/generator-keystone/pull/109.
(Non-core workarounds [here](https://github.com/keystonejs/generator-keystone/issues/98).)
 3. [ ] ? Configuration issue (@olhapi mentioned same error on different template: Users).


<br>
#### Longer:
I'm not sure if this closes #98. I originally thought that it was related (since you get the `ENOTFOUND` error since the template isn't in the expected path).
However, @olhapi mentions the same `ENOTFOUND` error for the users model. I'd guess there is a different issue (possibly configuration) happening there.

I left a long comment #98, hopefully will help where `ENOTFOUND` is due to the enquiry-notification template missing.

Additionally, I had an issue where the path that it was looking for the templates was wrong (workaround mentioned in the comment) but I'm not clear that that was a generator issue. It might be and it may be closed by https://github.com/keystonejs/generator-keystone/pull/109

So, merging https://github.com/keystonejs/generator-keystone/pull/109 then would tick two of the items and, if you assume that there is a configuration issue, one might close https://github.com/keystonejs/generator-keystone/issues/98. (Not sure what the Keystone community norms are on that.)

**Comment by ppiekarczyk** [comment]
:wave: if ya'll need me I'm right here! #109

**Pull request merged**
