### PR TITLE
fixed grunt lint to use .jshintrc file

### PR DESCRIPTION
**Pull request by kartsims**
Hi there,

I couldn't use grunt lint without this line in the linter's grunt file... Thought you would be happy to know

Thanks for the great work with this helpful generator for noobs like me

### CODE REVIEW

**Comment by JedWatson** [comment]
Thanks @kartsims, much appreciated!

**Comment by kartsims** [comment]
Hey @JedWatson I also have some issues/PR pending to add some documentation and got no answer yet, that is sad as good doc really helps guys like me to get going with Keystone !

FYI I am also developing an UI for BrowserStack that is intended for web agencies to provide the automate test results to their customers. Specs are based on our internal needs but I intend to open source the project as soon as I have something ready for production. This is based on Keystone so I can't thank you enough for making it easy... I wouldn't have even tried if I wasn't curious to try out your awesome framework

**Comment by morenoh149** [comment]
@kartsims please link to the PRs

**Comment by kartsims** [comment]
Sorry I had only one issue actually (guess I didn't file the other one) [here](https://github.com/keystonejs/keystonejs-site/issues/53)

**Pull request merged**
