### PR TITLE
Handlebars and express-handlebars version updated

### PR DESCRIPTION
**Pull request by divyabiyani**
It is a fix for #131 .

### CODE REVIEW

**Comment by mxstbr** [comment]
Are there no changes that affect us?

**Comment by divyabiyani** [comment]
@mxstbr Could you please tell me how to check that?

**Comment by mxstbr** [comment]
Run `$ yo keystone`, choosing handlebars and then seeing that everything works like before!

**Comment by divyabiyani** [comment]
@mxstbr Yes,I did check it.
Everything is working the same like before.

**Comment by mxstbr** [comment]
Thanks so much @divyabiyani!

**Pull request merged**
